SELECT "2025-05-17";

SELECT YEAR("2025-03-29");

SELECT MONTH(CURDATE());

SELECT DAY(CURDATE());

SELECT QUARTER(CURDATE());

SELECT MONTHNAME(CURDATE());

SELECT DAYNAME(CURDATE());

SELECT WEEK(CURDATE());

SELECT NOW();

SELECT CURDATE();

SELECT CURTIME();

SELECT DAYOFWEEK(CURDATE());

SELECT DATE_ADD(CURDATE() , INTERVAL 5 DAY);

SELECT DATE_ADD(CURDATE() , INTERVAL 6 MONTH);

SELECT DATE_ADD(CURDATE() , INTERVAL 6 QUARTER);

SELECT DATE_ADD(CURDATE() , INTERVAL 6 YEAR);

SELECT DATE_SUB(CURDATE() , INTERVAL 15 DAY);

SELECT DATEDIFF(CURDATE() ,"2025-11-01");

SELECT DATEDIFF("2025-11-10" , "2025-11-01");

SELECT DATE_FORMAT("2025-11-08" ,  "%W-%d-%M-%Y");

SELECT STR_TO_DATE("08-11-2025" ,  "%d-%M-%Y");

SELECT STR_TO_DATE("08-11-2025" ,  "%d-%m-%Y");

SELECT STR_TO_DATE("SATURDAY, 8TH/NOVEMBER/25" ,  "%W,%d/%M/%Y");

SELECT TIMESTAMPDIFF(YEAR , CURDATE() ,  "1995-02-18");

SELECT TIMESTAMPDIFF(QUARTER , CURDATE() ,  "01-04-2024");

SELECT "HALLO WORLD";

SELECT LENGTH("HALLO");

SELECT UPPER("hallo");

SELECT lower("HALLO");

SELECT TRIM("   HALLO   ");

SELECT LEFT("DATA SCIENCE" , 4);

SELECT RIGHT("DATA SCIENCE" , 7);

SELECT SUBSTRING("DATA ANALYTICS AND SCIENCE" , 6, 9);

SELECT REVERSE("HALLO");

SELECT REPEAT("HALLO  " , 3);

SELECT CONCAT("HALLO" , " "  , "WORLD" , " " , "INDIA");

SELECT CONCAT_WS( "--","HALLO" , "WORLD" , "INDIA");

SELECT LOCATE("SCIENCE" , "DATA  SCIENCE");

SELECT REPLACE("HALLO WORLD" , "WORLD" , "INDIA");


"%D"---"1ST"
"%d"---01

"%M"---11
"%M"---NOVEMBER

"%Y" ---- 2025



