CREATE DATABASE COMPANY;

USE COMPANY;

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR (20),
EMP_AGE INT (5),
EMP_DEPT VARCHAR (50),
EMP_CITY VARCHAR (20),
EMP_SALARY DECIMAL (10 , 2)
);


INSERT INTO EMPLOYEE
VALUES
(1 , "ROHIT" , 26 , "IT" , "MUMBAI" , 55000),
(2 , "MOHIT" , 29 , "SALES" , "DELHI" , 45000),
(3 , "KARAN" , 30 , "ADMIN" , "PUNE" , 40000),
(4 , "RAHUL" , 22 , "HR" , "HYDERABAD" , 25000),
(5 , "YASH" , 32 , "TECH" , "BANGALORE" , 84000),
(6 , "ADITYA" , 37 , "IT" , "PUNE" , 22000),
(7 , "KESHAV" , 24 , "HR" , "DELHI" , 60000),
(8 , "VIHAAN" , 36 , "SALES" , "CHANNI" , 45000),
(9 , "DHRUV" , 31 , "CUSTOMER SUPPORT" , "PUNJAB" , 77000),
(10 , "KISHAN" , 27 , "IT" , "PUNE" , 68000);


SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE EMP_SALARY > 70000;

SELECT * FROM EMPLOYEE
WHERE EMP_SALARY < 50000;

SELECT * FROM EMPLOYEE
WHERE EMP_CITY = "DELHI";

SELECT * FROM EMPLOYEE
WHERE EMP_CITY != "DELHI";

SELECT * FROM EMPLOYEE
WHERE EMP_CITY = "PUNE" AND EMP_DEPT = "IT";

SELECT * FROM EMPLOYEE
WHERE EMP_NAME = "ROHIT" AND EMP_DEPT = "IT" AND EMP_SALARY < 70000;

SELECT * FROM EMPLOYEE
WHERE EMP_SALARY >= 50000 AND EMP_SALARY < 70000;

SELECT * FROM EMPLOYEE
WHERE EMP_SALARY BETWEEN 50000 AND 70000;

SELECT * FROM EMPLOYEE
WHERE EMP_CITY =  "MUMBAI" OR EMP_CITY = "PUNE" OR EMP_CITY = "HYDERABAD";

SELECT * FROM EMPLOYEE
WHERE EMP_CITY =  "MUMBAI" OR EMP_CITY = "PUNE" OR EMP_CITY = "KOLKATA";

SELECT * FROM EMPLOYEE
WHERE EMP_CITY =  "MUMBAI" OR EMP_CITY = "PUNE" OR EMP_CITY = "KOLKATA";

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "A%";

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "%N";

SELECT * FROM EMPLOYEE
WHERE EMP_NAME LIKE "%O";

SELECT * FROM EMPLOYEE 
WHERE EMP_CITY = "DELHI"
ORDER BY EMP_SALARY DESC
LIMIT 1;

SELECT  * FROM EMPLOYEE
ORDER BY EMP_AGE ASC
LIMIT 1;

SELECT * FROM EMPLOYEE
WHERE EMP_CITY IN ("MUMBAI" , "PUNE" , "KOLKARA");

SELECT * FROM EMPLOYEE
WHERE EMP_CITY NOT IN ("DELHI" , "MUMBAI");

SELECT * FROM EMPLOYEE
WHERE EMP_DEPT =  "IT" AND EMP_DEPT = "TEACK";

SELECT * FROM EMPLOYEE
WHERE EMP_CITY =  "MUMBAI" OR EMP_CITY = "DELHI";

