# YE CHAPTER CLIYER HAI ..

CREATE DATABASE GREAT_EASTERN_RETAIL;

USE GREAT_EASTERN_RETAIL;

CREATE TABLE SALES(
ID INT PRIMARY KEY,
PRODUCT_NAME VARCHAR (100),
CATEGORY VARCHAR (50),
CITY VARCHAR (50),
QUANTITY_SOLD INT (10),
UNIT_PRICE INT (20)
);

SELECT * FROM SALES;

INSERT INTO SALES
VALUES
(1 , "LAPTOP" , "ELECTRONICS" , "DELHI" , 10 , 50000),
(2 , "SMARTPHONE" , "ELECTRONICS" , "MUMBAI" , 15 , 20000),
(3 , "HEADPHONES" , "ACCESSORIES" , "CHENNI" , 25 , 1500),
(4 , "KEYBORD" , "ACCESSORIES" , "DELHI" , 30 , 1000),
(5 , "MONITOR" , "ELECTRONICS" , "BANGALORE" , 5 , 12000),
(6 , "MOUSE" , "ACCESSORIES" , "MUMBI" , 40 , 700),
(7 , "SMARTWATCH" , "WEARABLES" , "KOLKATA" , 12 , 7000),
(8 , "TABLET" , "ELECTRONICS" , "HYDERABAD" , 8 , 18000),
(9 , "CHARGER" , "ACCESSORIES" , "PUNE" , 50 , 500),
(10 , "SPEAKERS" , "ACCESSORIES" , "DELHI" , 18 , 2500),
(11 ,"CAMERA" , "ELECTRONICS" , "MUMBAI" , 4 , 40000),
(12 , "TRIPOD" ,"ACCESSORIES" , "CHENNI" , 20 , 1200),
(13 , "LAPTOP" , "ELECTRONICS" , "DLHI" , 18 , 2500),
(14 , "SMARTPHONE" , "ELECTRONICS" , "BANGALOR" , 22 , 21000),
(15 , "MONITOR" , "ELECTRONICS" , "PUNE" , 3 , 11000),
(16 , "KEYBORD" , "ACCESSORIES" , "KOLKATA" , 15 , 900),
(17 , "MOUSE" , "ACCESSORIES" , "HYDERABAD" , 28 , 750),
(18 , "SMARTWATCH" , "WEARABLES" , "MUMBAI" , 10 , 6800),
(19 , "TABLET" , "ELECTRONICS" , "DELHI" , 7 , 17500),
(20 , "CHARGER" , "ACCESSORIES" , "CHENNAI" , 35 , 450);

SELECT * FROM SALES
WHERE CITY = "MUMBAI";

SELECT * FROM SALES
WHERE PRODUCT_NAME = "SMARTPHONE"
ORDER BY QUUANTITY_SOLD ASC;

SELECT PRODUCT_NAME, SUM(QUUANTITY_SOLD) AS TOTAL_QUUANTITY_SOLD
FROM SALES
GROUP BY PRODUCT_NAME;

SELECT CATEGORY, SUM(QUUANTITY_SOLD) AS TOTAL_QUUANTITY_SOLD
FROM SALES
GROUP BY CATEGORY
ORDER BY TOTAL_QUUANTITY_SOLD DESC;

SELECT category, SUM(quantity) AS total_quantity_sold
FROM sales
GROUP BY category
HAVING SUM(quantity) > 50;

SELECT CATEGORY, SUM(QUUANTITY_SOLD) AS TOTAL_QUUANTITY_SOLD
FROM SALES
GROUP BY CATEGORY 
HAVING SUM(QUUANTITY_SOLD) > 50; 

SELECT EMP_DEPERTMENT, AVG(EMP_SALARY) AS AVG_SALARY
FROM EMPLOYEE
WHERE EMP_SALARY BETWEEN 30000 AND 80000
GROUP BY EMP_DEPERTMENT;



SELECT PRODUCT_NAME , COUNT(SALES) AS TOTAL_ORDERS
FROM PRODUCT
GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME , COUNT(SALES) AS TOTAL_ORDERS
FROM PRODUCT
GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME , SUM(SALES) AS TOTAL_ORDERS
FROM PRODUCT
GROUP BY PRODUCT_NAME;

SELECT PRODUCT_NAME,
SUM(SALES) AS TOTAL_SALES,
AVG(SALES) AS AVERAGE_SALES,
MIN(SALES) AS MINIMUM_SALES,
MAX(SALES) AS MAXIMUM_SALES
FROM PRODUCT
GROUP BY PRODUCT_NAME;





