CREATE DATABASE COMP;

USE COMP;

CREATE TABLE EMPLOYEE(
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(20),
EMP_AGE INT,
EMP_DEPT VARCHAR(20), 
EMP_CITY VARCHAR(30),
EMP_SALARY INT
);


INSERT INTO EMPLOYEE
VALUES 
( 1, "Aarav" , 29 , "india", "IT" , 57925),
( 2, "Vivaan" , 26 , "india" , "Operations" , 64708),
( 3, "Aditya" , 25 , "india" , "Customer Support" , 75337),
( 4, "Vhaan" , 37 , "india" , "IT" , 66894),
( 5, "Arjun" , 27 , "india" , "admin" , 34067),
( 6, "Sai" , 30 , "india" , "IT" , 47205),
( 7, "Krishana" , NULL , "india" , "R&D" , 56851),
( 8, "Ishaan" , 30 , "india" , "IT" , 56128),
( 9, "Rohan" , 39 , "india" , "IT" , 37337),
( 10, "Kabir" , 38 , "india" , "IT" , 72853);

SELECT * FROM EMPLOYEE;

SELECT COUNT(*) AS TOTAL_EMPLOYEE
FROM EMPLOYEE;

SELECT SUM(EMP_SALARY) AS TOTAL_SALARIES
FROM EMPLOYEE;

SELECT MAX(EMP_SALARY) AS HIGHEST_SALARIES
FROM EMOLOYEE;

SELECT MAX(EMP_SALARY) AS OLDEST_SALARIES
FROM EMPLOYEE;

SELECT AVG(EMP_SALARY) AS AVERAGE_SALARIES
FROM EMPLOYEE;

SELECT
COUNT(EMP_ID) AS TOTAL_EMPLOYEE,
SUM(EMP_SALARY) AS TOTAL_SALARY,
AVG(EMP_SALARY) AS AVERAGE_EMP_SALARY,
MAX(EMP_SALARY) AS HIGHEST_SALARY, 
MIN(EMP_SALARY) AS LOWEST_SALARY
FROM EMPLOYEE;

SELECT DISTINCT EMP_DEPT FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
ORDER BY EMP_SALARY DESC
LIMIT 3;

SELECT EMP_NAME , EMP_AGE
FROM EMPLOYEE
ORDER BY EMP_AGE ASC
LIMIT 3;
